# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

service: serverless-with-next

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-jest-plugin

# Enable auto-packing of external modules
# See https://serverless-stack.com/chapters/add-support-for-es6-es7-javascript.html
custom:
  webpackIncludeModules:
    forceInclude:
      - next

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
#  memorySize: 3008
  timeout: 30

package:
  individually: true

# The `functions` block defines what code to deploy
functions:
  server:
    handler: lambdas/server.handler
    events:
      - http:
          method: get
          path: /
      - http:
          method: get
          path: /_next/{proxy+}
#    package:
#      include:
#        - ../.next/**
#        - ../static/**
